=== monicatvera/Beach-predictions-of-las-canteras/play_v2_3501601_output.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="playa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="predicciones">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dia" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="estado_cielo"/>
                                        <xs:element type="xs:string" name="viento"/>
                                        <xs:element type="xs:string" name="oleaje"/>
                                        <xs:element type="xs:string" name="t_maxima"/>
                                        <xs:element type="xs:string" name="s_termica"/>
                                        <xs:element type="xs:int" name="t_agua"/>
                                        <xs:element type="xs:int" name="uv_max"/>
                                    </xs:sequence>
                                    <xs:attribute type="xs:int" name="fecha" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="nombre" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== monicatvera/Beach-predictions-of-las-canteras/play_v2_3501601_output.xml
<?xml version="1.0" encoding="UTF-8"?>
<playa nombre="Las Canteras" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="play_v2_3501601_output.xsd">
    <predicciones>
        <dia fecha="20200416">
            <estado_cielo>nuboso</estado_cielo>
            <viento>flojo</viento>
            <oleaje>flojo</oleaje>
            <t_maxima/>
            <s_termica>suave</s_termica>
            <t_agua>20</t_agua>
            <uv_max>9</uv_max>
        </dia>
        <dia fecha="20200417">
            <estado_cielo>despejado</estado_cielo>
            <viento>flojo</viento>
            <oleaje>flojo</oleaje>
            <t_maxima/>
            <s_termica>suave</s_termica>
            <t_agua>22</t_agua>
            <uv_max>9</uv_max>
        </dia>
        <dia fecha="20200418">
            <estado_cielo>nuboso</estado_cielo>
            <viento>flojo</viento>
            <oleaje>flojo</oleaje>
            <t_maxima/>
            <s_termica>suave</s_termica>
            <t_agua>22</t_agua>
            <uv_max>7</uv_max>
        </dia>
    </predicciones>
</playa>
